---
name: new AP Request
description: just testing template
title: 'this is a title'
labels: 'this is a label'
assignees: 'me'

body:
- type: markdown
  attributes:
    value : "this is a value"
- type : textarea
  attributes:
    label: this is a label
    description: this is a description 
    placeholder: this is a placeholder
  validations :
    required: true
