---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

body :
-type : markdown
    attributes :
        label : What happen
        description : nothing i guess
        placeholder : what is placeholder
    validations :
        required : true
